# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 고현종
title: 게임 개발자
email: ghj1014@naver.com
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hyeonjongko

# Additional icon links
additional_links:
- title: README
  icon: <FontAwesomeIcon icon="fa-solid fa-info" />
  url: https://github.com/hyeonjongko
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)

about_content: | # this will include new lines to allow paragraphs
    안녕하세요 저는 게임 개발을 위해 공부를 하고있는 빅데이터 고현종입니다.
    - 성격 : 활발하고 긍정적이며 끈기가 강하다.
    - 취미 : 여러 장르의 게임 하기
    - 특기 : 남의 이야기를 잘 들어준다.
    
    ![Profile](https://user-images.githubusercontent.com/115774307/198256677-58230a50-0330-4561-bc28-31269fccd13f.jpg){: width="40%" height="40%"}
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 점프게임

        quote: >
          게임요약 : 탑안에 발판을 올라가 정상의 보물상자를 획득하는 게임.
        description: | # this will include new lines to allow paragraphs
          ![game_1](https://user-images.githubusercontent.com/115774307/198257166-7ab9d1a0-e593-4cc7-98a0-ea71c6198eea.jpg){: width="50%" height="30%"}
          
          게임 시작 화면
          
          ![game_2](https://user-images.githubusercontent.com/115774307/198257486-f11f0765-9762-4737-bd0c-27fd3e5933be.jpg){: width="50%" height="30%"}
          
          게임 플레이 화면1
          
          ![game_3](https://user-images.githubusercontent.com/115774307/198257567-25c5578a-2aa1-4638-9706-c45846e9a742.jpg){: width="50%" height="30%"}
          
          게임 플레이 화면2
          
          ![game_4](https://user-images.githubusercontent.com/115774307/198257789-75a5c144-9439-4931-83b8-3186ffec8329.jpg){: width="50%" height="30%"}
          
          게임의 보물상자를 획득하는 화면
          
          ![game_5](https://user-images.githubusercontent.com/115774307/198257880-553f7ed6-94e5-4f44-acc9-5e0d2ef81116.jpg){: width="50%" height="30%"}
          
          게임 종료화면

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: 한림대학교
        caption: 2018 - 2022
        quote: >
          Unity Engine
           -C#
          /Unreal Engine
           -C++
          /Other
           -Java,
           -Python,
           -C,
           -Flutter,
           -Arduino
        description: | # this will include new lines to allow paragraphs
          게임을 제작하기 위한 엔진들을 학습하며 그 엔진들에 필요한 언어를 학습.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     현재는 게임 개발을 위해 Unreal 엔진을 학습하며 여러가지 게임을 취미로 플레이하며 내가 만들고 싶은 게임의 정보들을 확인하 학습을 하고 있다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
